apiVersion: v1
kind: Service
metadata:
  name: test_app_1-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: service1
      nodePort: 9394
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: test_app_1
  sessionAffinity: None
  type: NodePort
